version: 1
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  request:
    format: "%(asctime)s - %(levelname)s - %(client_addr)s - %(method)s %(path)s - Body: %(body)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: request
    filename: server_logs.txt
loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: False
  uvicorn.access:
    handlers: [console, file]
    level: INFO
    propagate: False
root:
  handlers: [console, file]
  level: INFO